// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: factorialiser.proto

package factorialiser

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FactorialiseFloatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *float32 `protobuf:"fixed32,1,req,name=a" json:"a,omitempty"`
}

func (x *FactorialiseFloatMessage) Reset() {
	*x = FactorialiseFloatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factorialiser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactorialiseFloatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorialiseFloatMessage) ProtoMessage() {}

func (x *FactorialiseFloatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_factorialiser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorialiseFloatMessage.ProtoReflect.Descriptor instead.
func (*FactorialiseFloatMessage) Descriptor() ([]byte, []int) {
	return file_factorialiser_proto_rawDescGZIP(), []int{0}
}

func (x *FactorialiseFloatMessage) GetA() float32 {
	if x != nil && x.A != nil {
		return *x.A
	}
	return 0
}

type FactorialiseFloatResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R *float32 `protobuf:"fixed32,1,req,name=r" json:"r,omitempty"`
}

func (x *FactorialiseFloatResult) Reset() {
	*x = FactorialiseFloatResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factorialiser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactorialiseFloatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorialiseFloatResult) ProtoMessage() {}

func (x *FactorialiseFloatResult) ProtoReflect() protoreflect.Message {
	mi := &file_factorialiser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorialiseFloatResult.ProtoReflect.Descriptor instead.
func (*FactorialiseFloatResult) Descriptor() ([]byte, []int) {
	return file_factorialiser_proto_rawDescGZIP(), []int{1}
}

func (x *FactorialiseFloatResult) GetR() float32 {
	if x != nil && x.R != nil {
		return *x.R
	}
	return 0
}

var File_factorialiser_proto protoreflect.FileDescriptor

var file_factorialiser_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x18, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x73, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x61, 0x22,
	0x27, 0x0a, 0x17, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x73, 0x65, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x72, 0x32, 0x56, 0x0a, 0x0d, 0x46, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x73, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0e, 0x46, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x19, 0x2e, 0x46, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x73, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x73, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
}

var (
	file_factorialiser_proto_rawDescOnce sync.Once
	file_factorialiser_proto_rawDescData = file_factorialiser_proto_rawDesc
)

func file_factorialiser_proto_rawDescGZIP() []byte {
	file_factorialiser_proto_rawDescOnce.Do(func() {
		file_factorialiser_proto_rawDescData = protoimpl.X.CompressGZIP(file_factorialiser_proto_rawDescData)
	})
	return file_factorialiser_proto_rawDescData
}

var file_factorialiser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_factorialiser_proto_goTypes = []interface{}{
	(*FactorialiseFloatMessage)(nil), // 0: FactorialiseFloatMessage
	(*FactorialiseFloatResult)(nil),  // 1: FactorialiseFloatResult
}
var file_factorialiser_proto_depIdxs = []int32{
	0, // 0: Factorialiser.FactorialFloat:input_type -> FactorialiseFloatMessage
	1, // 1: Factorialiser.FactorialFloat:output_type -> FactorialiseFloatResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_factorialiser_proto_init() }
func file_factorialiser_proto_init() {
	if File_factorialiser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_factorialiser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactorialiseFloatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_factorialiser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactorialiseFloatResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_factorialiser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_factorialiser_proto_goTypes,
		DependencyIndexes: file_factorialiser_proto_depIdxs,
		MessageInfos:      file_factorialiser_proto_msgTypes,
	}.Build()
	File_factorialiser_proto = out.File
	file_factorialiser_proto_rawDesc = nil
	file_factorialiser_proto_goTypes = nil
	file_factorialiser_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FactorialiserClient is the client API for Factorialiser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FactorialiserClient interface {
	FactorialFloat(ctx context.Context, in *FactorialiseFloatMessage, opts ...grpc.CallOption) (*FactorialiseFloatResult, error)
}

type factorialiserClient struct {
	cc grpc.ClientConnInterface
}

func NewFactorialiserClient(cc grpc.ClientConnInterface) FactorialiserClient {
	return &factorialiserClient{cc}
}

func (c *factorialiserClient) FactorialFloat(ctx context.Context, in *FactorialiseFloatMessage, opts ...grpc.CallOption) (*FactorialiseFloatResult, error) {
	out := new(FactorialiseFloatResult)
	err := c.cc.Invoke(ctx, "/Factorialiser/FactorialFloat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FactorialiserServer is the server API for Factorialiser service.
type FactorialiserServer interface {
	FactorialFloat(context.Context, *FactorialiseFloatMessage) (*FactorialiseFloatResult, error)
}

// UnimplementedFactorialiserServer can be embedded to have forward compatible implementations.
type UnimplementedFactorialiserServer struct {
}

func (*UnimplementedFactorialiserServer) FactorialFloat(context.Context, *FactorialiseFloatMessage) (*FactorialiseFloatResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FactorialFloat not implemented")
}

func RegisterFactorialiserServer(s *grpc.Server, srv FactorialiserServer) {
	s.RegisterService(&_Factorialiser_serviceDesc, srv)
}

func _Factorialiser_FactorialFloat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactorialiseFloatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactorialiserServer).FactorialFloat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Factorialiser/FactorialFloat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactorialiserServer).FactorialFloat(ctx, req.(*FactorialiseFloatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Factorialiser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Factorialiser",
	HandlerType: (*FactorialiserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FactorialFloat",
			Handler:    _Factorialiser_FactorialFloat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "factorialiser.proto",
}
